# Generated by Django 3.0.3 on 2020-02-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20200219_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.PositiveIntegerField(choices=[(1, 'BBC'), (2, 'NY Times'), (3, 'Russia Today')], unique=True),
        ),
    ]
